### ISSUE TITLE
create raw object 

### ISSUE THREAD

**Issue by mluerig** [CINPLA/exdir#66]
hey, I may have missed it in the documents, but i) how I can create a "raw" group and ii) how I can update or remove a data set?

**Comment by dragly** [comment]
Raw objects currently can only be created by making a new directory (for instance using os.mkdir - correct me if I'm wrong @lepmik @miladh), so that's an oversight on our part. We should definitely have a `create_raw` and `require_raw` function on a group object.

To update a dataset, you can use the setter on a group object. This is definitely missing from the documentation, so thank you for pointing that out.

```
my_group['my_dataset'] = np.array([1, 2, 3, 4])
```

As for deleting datasets, this currently is not implemented, but you can remove a dataset by deleting its directory. We will make sure to implement this in the next release.

**Comment by lepmik** [comment]
Closing this, `create_raw` and `require_raw` is now implemented, update dataset is documented. Deleting datasets are being implemented and has it's own issue #83
